### ISSUE TITLE
New Fork / Project

### ISSUE THREAD

**Issue by GrantBirki** [watzon/octokit.cr#14]
Hi folks! 👋

I went ahead and moved this project over to https://github.com/GrantBirki/octokit.cr. I kinda just assumed that this project isn't being actively worked on since the last commit was over three years ago. If that is not the case, and you would like me to contribute my changes back here let me know. Or if you would like me to continue working on it on my own, let me know.

I have already published a new version of the project that implements `deployments` on-par with `octokit.rb` and I plan on continuing out more features in the near future.

**Comment by watzon** [comment]
Since this project is already here I'd be happy to merge any changes you have. I'd also be more than happy to add you as a contributor.

**Comment by GrantBirki** [comment]
Oh fantastic! In that case, if you would make me a contributor, that would be excellent 🎉

**Comment by GrantBirki** [comment]
If I have `write` access, that will make things 1000x easier. I can start with opening a fork with my changes though if that works best for you to review @watzon

**Comment by GrantBirki** [comment]
Alternatively, we could also follow the "put it into a new GitHub organization" approach for better management of it. That way it isn't directly tied to a single person's account but rather an org with several maintainers.

**Comment by GrantBirki** [comment]
This would be my preferred approach tbh, just having a `octokit.cr` organization with the project living under there 😃

**Comment by GrantBirki** [comment]
Made this in case you want to use it -> https://github.com/octokit-cr

**Comment by watzon** [comment]
Sure, I'm down for the organization approach. Just give me access and I'll transfer this project there.

**Comment by GrantBirki** [comment]
Invite set!

**Comment by watzon** [comment]
Transfer complete
