### ISSUE TITLE
Failure when running tests

### ISSUE THREAD

**Issue by curquiza** [watzon/octokit.cr#2]
On `master`, when doing:

```bash
$ shards install
...
$ crystal spec

....

In lib/halite/src/halite/features/logging/json.cr:47:28

 47 | @request_time = Time.now
                           ^--
Error: undefined method 'now' for Time.class

Did you mean 'new'?
```

**Comment by watzon** [comment]
Ok so this was written several versions back. I would ideally like to get rid of Halite and replace it with the built in `HTTP::Client` (it's much faster). This particular error is because `Time.now` was removed though.
